[package]
name = "asylum"
version = "0.1.0"
authors = ["Syn-Nine <contact@syn-nine.com>"]
edition = "2018"
metadata.html.template = "../../template.html"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
